language: python
matrix:
    include:
        - python: 2.7
          env: TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
        - python: 3.4
          env: TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp34-cp34m-linux_x86_64.whl
install:
    - pip install .
script:
    - pytest
notifications:
    email: false